name: MLflow Training & Docker CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/MuhammadMirzaRalfie/Eksperimen_SML_Mirza.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  REPO_NAME: eksperimen-sml-mirza  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout Code
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Dependencies
    - name: Install dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn virtualenv

    # 4. Run MLflow Project ]
    - name: Run mlflow project
      run: |
        cd Workflow-CI/MLProject
        
        mlflow run . --env-manager=local --experiment-name "Eksperimen_RF_Automated"

    # 5. Get Latest Run ID 
    - name: Get latest MLflow run_id
      id: get_run
      run: |
        
        RUN_ID=$(mlflow runs list --experiment-id $(mlflow experiments search --view active_only | grep "Eksperimen_RF_Automated" | awk '{print $1}') | head -n 3 | tail -n 1 | awk '{print $4}')
        echo "Detected Run ID: $RUN_ID"
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    # 6. Build Docker Model 
    - name: Build Docker Model
      run: |
        echo "Building Docker Image from Run ID: ${{ steps.get_run.outputs.run_id }}"
        # Membungkus model hasil training menjadi Docker Image siap pakai
        mlflow models build-docker --model-uri "runs:/${{ steps.get_run.outputs.run_id }}/model" --name ${{ env.REPO_NAME }}

    # 7. Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 8. Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag ${{ env.REPO_NAME }} ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:latest
        docker tag ${{ env.REPO_NAME }} ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:${{ github.sha }}

    # 9. Push Docker Image ke Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:latest
        docker push ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:${{ github.sha }}