name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ml-env
        environment-file: Workflow-CI/MLProject/conda.yaml
        python-version: "3.10"
        auto-activate-base: false

    - name: Verify environment
      run: |
        conda info
        conda list

    - name: Run MLflow Project Train Job
      run: |
        mlflow run Workflow-CI/MLProject

    - name: Locate MLflow Model Path
      id: find_model
      run: |
        LAST_MODEL=$(find Workflow-CI/MLProject/mlruns -type d -path "*/artifacts/model" | tail -n 1)
        echo "model_path=$LAST_MODEL" >> $GITHUB_OUTPUT

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: ${{ steps.find_model.outputs.model_path }}

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image using MLflow
      run: |
        mlflow models build-docker \
          -m "${{ steps.find_model.outputs.model_path }}" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model:latest"

    - name: Push Docker Image to Docker Hub
      run: |
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model:latest"
