name: MLflow Training & Docker CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/MuhammadMirzaRalfie/Eksperimen_SML_Mirza.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  REPO_NAME: eksperimen-sml-mirza

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install mlflow==2.14.1 dagshub pandas scikit-learn matplotlib seaborn virtualenv

    - name: Run MLflow & Capture ID
      id: get_run
      run: |
        cd Workflow-CI/MLProject || cd MLProject
        
        mlflow run . --env-manager=local --experiment-name "Eksperimen_RF_Automated" > output.log 2>&1
        cat output.log
        
        RUN_ID=$(grep "Run ID saved:" output.log | awk '{print $NF}')
        
        if [ -z "$RUN_ID" ]; then
          echo "ERROR: Run ID not found."
          exit 1
        fi
        
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Build Docker Model
      run: |
        mlflow models build-docker --model-uri "runs:/${{ steps.get_run.outputs.run_id }}/model" --name ${{ env.REPO_NAME }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag ${{ env.REPO_NAME }} ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:latest
        docker tag ${{ env.REPO_NAME }} ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:${{ github.sha }}
        docker push ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:latest
        docker push ${{ env.DOCKER_USER }}/${{ env.REPO_NAME }}:${{ github.sha }}