name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ml-env
        environment-file: Workflow-CI/MLProject/conda.yaml
        python-version: "3.10"
        auto-activate-base: false

    - name: Verify environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
        which python
        python -c "import mlflow; print('MLflow OK')"

    - name: Run MLflow Project (Training)
      working-directory: Workflow-CI/MLProject
      shell: bash -l {0}
      run: |
        python -m mlflow run .

    - name: Find latest MLflow model artifact
      id: findmodel
      shell: bash -l {0}
      run: |
        LAST_MODEL=$(find mlruns -type d -path "*/artifacts/model" | tail -n 1)
        echo "model_path=$LAST_MODEL" >> $GITHUB_OUTPUT

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: ${{ steps.findmodel.outputs.model_path }}

    - name: Login to Docker Hub
      shell: bash -l {0}
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image using MLflow
      shell: bash -l {0}
      run: |
        mlflow models build-docker \
          -m ${{ steps.findmodel.outputs.model_path }} \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model:latest"

    - name: Push Docker Image to Docker Hub
      shell: bash -l {0}
      run: |
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model:latest"
